### PR TITLE
[Fix] Fix publish workflow error by renaming wheel file

### PR DESCRIPTION
**Pull request by LazyBusyYang**
1. New start condition for publish workflow. Either branch name or tag works. Here's an [example](https://github.com/openxrlab/xrprimer/actions/runs/4795935957) triggered by tag.
2. Replace twine username from `__token__` to `secrets.PYPI_USERNAME`, works well in forked repo.

### CODE REVIEW

**Comment by LazyBusyYang** [comment]
Merge python version matrix into one loop: Failed.
Still telling me the same message:
```ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         This filename has already been used, use a different version. See      
         https://pypi.org/help/#file-name-reuse for more information.  
```
See details: https://github.com/LazyBusyYang/xrprimer/actions/runs/4795382169/jobs/8529863990

**Comment by LazyBusyYang** [comment]
Due to suspicion of naming issues, I tried renaming and uploading. At the first time I still received the same failure message.
twine_upload_fail
At the second time it succeed but I don't know why.
image

**Comment by LazyBusyYang** [comment]
Suspicion: All names for 0.6.1 have been used(uploaded before), and deleting a release does not help. Upload wheel to a new release may work.
Experiment(upload to 0.5.9):
https://github.com/LazyBusyYang/xrprimer/actions/runs/4796713895/jobs/8532808543
Conclusion: 0.6.1 can never be used. Another version is OK.

**Comment by LazyBusyYang** [comment]
Time consumption between loop and strategy matrix:
[loop](https://github.com/LazyBusyYang/xrprimer/actions/runs/4796713895/jobs/8532808543): 15min 59 sec
[strategy matrix](https://github.com/LazyBusyYang/xrprimer/actions/runs/4797676248/jobs/8534963482): 10min 38ssec

**Review by yl-1993 — APPROVED** [review]

**Pull request merged**
